[build-system]
requires = ["uv_build>=0.8.3"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "arservercontroller"
module-root = ""

[project]
name = "arservercontroller"
version = "0.1.0"
description = "Arma Reforger Dedicated Server container manager."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.4",
    "docker>=7.1.0",
    "fastapi[standard]>=0.116.1",
    "pydantic-extra-types>=2.10.5",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.41",
    "types-docker>=7.1.0.20250705",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "pytest-mock>=3.14.1",
]

[project.scripts]
arservercontroller = "arservercontroller.main:main"
