"""Map snake_case to camelCase for Server model fields

Revision ID: 4214dbd6cf9b
Revises: a91d51dca5df
Create Date: 2026-04-08 20:33:22.906709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4214dbd6cf9b'
down_revision: Union[str, Sequence[str], None] = 'a91d51dca5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'created_at', new_column_name='createdAt')
    op.alter_column('servers', 'updated_at', new_column_name='updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'createdAt', new_column_name='created_at')
    op.alter_column('servers', 'updatedAt', new_column_name='updated_at')
    # ### end Alembic commands ###
